WebApplication1/WebApplication1/Controllers/Data1Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.ViewModel;
namespace WebApplication1.Controllers
{
    public class Data1Controller : Controller
    {
        Datacon op = new Datacon();
        public IActionResult Index()
        {
            List<Department> dp = op.Departments.ToList();
            //Search for Inculde to get Departments with Their Students

            //return View("Index",dp);   //View=Index ,Model dp
            //return View(dp);           //View=Index ,Model dp
            //return View();             //View=Index ,Model null
            //return View("Index");      //View=Index ,Model null
            return View(dp);
        }

        //=================================================================
        public IActionResult Index2()
        {
            List<string> items = new List<string>();
            items.Add("TV");
            items.Add("Wach");
            items.Add("Ps4");
            items.Add("club");

            string col = "red",name = "PATO";
            int temp = 44;
            
            //ViewData must do casting in View file but ViewBag not

            ViewData["Tempreature"] = temp;
            ViewData["listt"] = items;
            ViewBag.colour = col;

            return View();
        }

        
        public IActionResult Index3()
        {
            List<string> items = new List<string>();
            items.Add("TV");
            items.Add("Wach");
            items.Add("Ps4");
            items.Add("club");

            string col = "violet", name = "PATO";
            int temp = 44;

            //ViewData must do casting in View file but ViewBag not

            ViewData["Tempreature"] = temp;
            ViewData["listt"] = items;
            ViewBag.colour = col;


            TestViewModel op = new TestViewModel();
            op.color = col;
            op.Items = items;
            op.Name = name;
            return View(op);

            // ViewModel  :Class data need to send to View      
            //add extra info
            //merge between 2 Model
            // filter property 
        }


        //=================================================================
        //Cockies video 6 
        public IActionResult SetTempData() {
            TempData["msg"] = "Message Hellow";
            return Content("Data saved");
        }
        public IActionResult GetTempData()
        {
            string ret = "Empty message";
            if (TempData.ContainsKey("msg"))
            {
                  ret = TempData["msg"].ToString();
                //ret = TempData.Peek("msg").ToString();  // Peek dont delete it after set

                //TempData.Keep();        keep it dont delete any tempdata
                //TempData.Keep("sadf");  keep it dont delete this spasific tempdata

            }
            return Content(ret);
        }
        public IActionResult SetSession() {                     // can get from any controller
            HttpContext.Session.SetString("Ahmed", "PATO");
            HttpContext.Session.SetInt32("age", 21);

            return Content("Set Done");
        }
        public IActionResult GetSession()
        {
            string name = HttpContext.Session.GetString("Ahmed");
            int age =HttpContext.Session.GetInt32("age").Value; //.Value to get value becuse GetInt allaow null  or make int? ___

            return Content($"data name ={name}   age = {age}");
        }
        public IActionResult SetCookies()                   // can get from any controller
        {
            CookieOptions options = new CookieOptions();

            options.Expires = DateTimeOffset.Now.AddHours(1);

            Response.Cookies.Append("Ahmed", "PATO", options);
            Response.Cookies.Append("age", "21");

            return Content("Cookies Done");
        }
        public IActionResult GetCookies()
        {
            string name = Request.Cookies["Ahmed"];
            int age = int.Parse(Request.Cookies["age"]);

            return Content($"From cookies  {name} {age}");
        }

        //=================================================================

        //Model Binding :Map Action Parametere with request data (FormData - QueryString - RouteData) Video 7
        // URL Data1/TestPrimitive?id=3&name=ahmed&age=21&age=21&colo[1]=red&colo[0]=blue
        public IActionResult TestPrimitive(int id, string name,int age,string[] colo)
        {
            return Content($"ID = {id}  Name = {name} age = {age}");
        }

        // URL Data1/Collection?name=Ahmed&phone[ahmed]=321&phone[pato]=123
        public IActionResult Collection(Dictionary<string,int>phone, string name)
        {
            return Content($"Name = {name}  phone[ahmed]= {phone["ahmed"]}   phone[pato]= {phone["PATO"]}   ");
        }

        // URL Data1/TestComplex?
        //Data1/TestComplex?vec_st[0].name=ahmed&vec_st[0].id=1&vec_st[1].name=pato&vec_st[1].id=2&name=toto
        public IActionResult TestComplex(Department dep)    //([Bind(include:"Id,Name")]Department dep) for Filter onlyyou want to bind
        {
            return Content("Saved Done");
        }

        //=================================================================

        IStudents_properties stpro = new Students_properties(); // Why use interface? To Make Dependency Inversion Principle  video row 3 last video min 40
        public IActionResult JoinUs() {
            List<Students> lst = stpro.Get_All();
            return View(lst);
        }
        
        // Anchor tag open empty form
        // Submit
        public IActionResult SignUp(){
            ViewData["deplst"] = op.Departments.ToList();
            return View(new Students());// form Sign
        }
        public IActionResult Edit(int id)
        {
            Students st = stpro.GetByID(id);
            ViewData["deplst"] = op.Departments.ToList();
            return View(st);            // form Edit
        }

        // Submit Button==>store data in database
        // to didnt add the row from link
        [HttpPost]
        public IActionResult SaveData(Students st)
        {
            if (ModelState.IsValid)
            {
                stpro.Insert(st);
                return RedirectToAction("JoinUs");  //RedirectToAction  becuse view JoinUs return object
            }
            else
            {
                ViewData["deplst"] = op.Departments.ToList();
                return View("SignUp",st);
            }
        }

        [HttpPost]
        public IActionResult SaveData2(int id ,Students st)
        {
            if (ModelState.IsValid)
            {
                stpro.Update(id, st);
                
                return RedirectToAction("JoinUs");  //RedirectToAction  becuse view JoinUs return object
            }
            else
            {
                ViewData["deplst"] = op.Departments.ToList();
                return View("Edit", st);
            }
        }
    }
}

WebApplication1/WebApplication1/Views/Data1/Edit.cshtml
@model Students
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<style>
    #a1 {
        background-color: beige;
        color: cornflowerblue;
    }

    #a2 {
        background-color: beige;
        color: crimson;
    }
</style>

<form id="a2" method="post" action="/Data1/SaveData2/@Model.Id">
    <!--  <div asp-validation-summary="All"></div>   This for show all unvalid inputes in Form-->

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" class=" form-control" style=" color:orangered" />
        <span asp-validation-for="Name"></span>
    </div>
    <br />

    <div>
        <label asp-for="Salary"></label>
        <input asp-for="Salary" class=" form-control" />
        <span asp-validation-for="Salary"></span>
    </div>
    <br />

    <div>
        <label asp-for="City"></label>
        <input asp-for="City" class=" form-control" style=" color:fuchsia" />
        <span asp-validation-for="City"></span>
    </div>
    <br />

    <div>   <!--Label by this way go to class and read the Display Name-->
        <label asp-for="course" style="color:blue"></label>      <!--Tag Helper-->    <!--The Best Way in Form-->
        <input asp-for="course" class=" form-control" style=" color:blue" placeholder="Enter ur course" />
        <span asp-validation-for="course"></span>
    </div>
    <br />

    <div>
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class=" form-control" style=" color:blue" placeholder="Enter ur Phone Number" />
        <span asp-validation-for="Phone"></span>
    </div>
    <br />

    <div>
        <label asp-for="Dep_id"></label>
        <select name="Dep_id">
            @foreach(Department dep in ViewBag.deplst){
               <option value="@dep.Id">@dep.Name</option>
            }
        </select>
    </div>
    <br />
    
    <input id="a1" type="submit" value="Save Changes" class="btn btn-success"/>
</form>

<partial name="_ValidationScriptsPartial" />

WebApplication1/WebApplication1/Views/Data1/Index.cshtml
@model List<Department>
@{
    ViewData["Title"] = "Index";
}

<style>
    #a1{
        
        background-color: blue;
        width :100%;  
    }
</style>

<h1>Index</h1>

<table id="a1" ,class="table table-bordered table-hover" background-color: rgba(150, 212, 212, 0.4)>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Maneger Name</th>
    </tr>

    @foreach (var i in Model)
    {
    <tr>
            <th>@i.Id</th>
            <th>@i.Name</th>
            <th>@i.Maneger_name</th>
    </tr>
    }

</table>

WebApplication1/WebApplication1/Views/Data1/Index2.cshtml
<h1>Index2</h1>

<h1>Test ViewData<h1/>

    <h2 style="background-color : @ViewData["colour"]">My color</h2>

<select>

        @foreach(var i in (List<string>)ViewData["listt"])
        {
            <option>@i</option>
        } 
</select>

<select>

        @foreach (var i in ViewBag.listt)
        {
            <option>@i</option>
        }

</select>

<hr>

    @((int)ViewData["Tempreature"] + 3)
    <br />
    @(ViewBag.Tempreature + 6)

WebApplication1/WebApplication1/Views/Data1/Index3.cshtml
@using WebApplication1.ViewModel


@{
    ViewData["Title"] = "Index3";
}

<h1>Index3 TestViewModel</h1>
<br>

@foreach(var i in Model.Items)
{
    <h3 style="color:@Model.color">@i</h3>
}

WebApplication1/WebApplication1/Views/Data1/JoinUs.cshtml
@model List<Students>
@{
    ViewData["Title"] = "JoinUs";
}


<h1>Join Us!!</h1>
</br>

<h2>
   <ol>
 Courses :
 <br /><br />

        <font color="Blue">
        <li>Web Site</li></font>
    </br>
        <font color="red">
        <li>Flutter</li></font>
    </br>
        <font color="green">
        <li>Net Work</li></font>
    </br>
        <font color="orange">
        <li>Cyber Security</li></font>
    </br>

        <font color="yellow">
        <li>Data Structure</li></font>
        <br />
        <font color="red">
        <li>Algorithms</li></font>
        <br />
        <font color="cyan">
        <li>Data Base</li></font>
    </ol>
    <hr />

</h2>
</br>

<a asp-controller="Data1" asp-action="SignUp">Apply Here</a>
<!--<a href="/Data1/SignUp">Apply Here</a>-->
</br>


</br>

<style>

    #a1 {
      
        background-color: cyan;
        width :100%;
        
    }
    #a2{
        background-color:blueviolet;
        color:aquamarine
    }

    #a3{
        color:blue;
        background-color :red;
    }
</style>

<table id="a1" ,class="table table-bordered table-hover" background-color: rgba(150, 212, 212, 0.4) >
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Salary</th>
        <th>City</th>
        <th>Courses</th>
        <th>Phone</th>
        <th>Dep_ID</th>
    </tr>

    @foreach (var i in Model)
    {
        <tr id="a2">
            <th>@i.Id</th>
            <th>@i.Name</th>
            <th>@i.Salary</th>
            <th>@i.City</th>
            <th>@i.course</th>
            <th>@i.Phone</th>
            <th>@i.Dep_id</th>
             <td id="a3"><a href="/Data1/Edit/@i.Id">Edit Here</a></td>
        </tr>
    }

</table>

WebApplication1/WebApplication1/Views/Data1/SignUp.cshtml
@model Students
@{
    ViewData["Title"] = "SignUp";
    SelectList lst = new SelectList(ViewBag.deplst, "Id", "Name");
        <!--Video 10 min 15-->
}

<style>   
    #a1{
        background-color:lawngreen;
        color:blue;
    }
    #a2{
        background-color:aqua;
        color:blue;
        width:500px;
        
    }

   
</style>

<form method="post" action="/Data1/SaveData">
    <!--  <div asp-validation-summary="All"></div>   This for show all unvalid inputes in Form-->

    <div id="a2" >

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" style="color:blue" class="form-control"/>
        <span asp-validation-for="Name"></span>
    </div>
    <br/>
   
    <div>
        <label asp-for="Salary" style="color:brown"></label>
        <input asp-for="Salary" style="color:aquamarine" class="form-control"/>
        <span asp-validation-for="Salary"></span>
    </div>
    <br/>

    <div>
        <label asp-for="City"></label>
        <input asp-for="City" style="color:green" class="form-control" />
        <span asp-validation-for="City"></span>
    </div>
    <br />

    <div>
        <label asp-for="course"></label>
        <input asp-for="course" style="color:violet" class="form-control" />
        <span asp-validation-for="course"></span>
    </div>
    <br/>
    
    <div>
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control"/>
        <span asp-validation-for="Phone"></span>
    </div>
    <br/>
    
    

    <div>
         <label asp-for="Dep_id"></label>     <!--Video 10 min 15-->
         <select
             asp-for="Dep_id" asp-items="lst" >
         </select>
    </div>
    <br />
    </div>

    <input id="a1" type="submit" value="Sign up" class="btn btn-success"/>
</form>

<partial name="_ValidationScriptsPartial" />